#!/bin/bash

# PlayStation DNS Setup Script
# Configures dnsmasq to redirect PlayStation domains to local server

set -e

echo "=== PlayStation DNS Setup ==="
echo

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "This script requires root privileges."
    echo "Please run: sudo ./setup-dnsmasq.sh"
    exit 1
fi

# Create dnsmasq configuration
echo "Creating dnsmasq configuration..."
cat > /etc/dnsmasq.d/playstation.conf << 'EOF'
# PlayStation Network domains - redirect to local server (192.168.10.200)
# Generated by PlayStation DNS Setup

# PS3 Update Servers
address=/fus01.ps3.update.playstation.net/192.168.10.200
address=/fj00.ps3.update.playstation.org/192.168.10.200

# PlayStation Network Services
address=/sf.prod.sonyentertainmentnetwork.com/192.168.10.200

# STUN Servers
address=/us.np.stun.playstation.net/192.168.10.200

# Download Servers
address=/a0.ww.np.dl.playstation.net/192.168.10.200

# Wildcard entries for all PlayStation domains
address=/playstation.net/192.168.10.200
address=/playstation.com/192.168.10.200
address=/playstation.org/192.168.10.200
address=/sonyentertainmentnetwork.com/192.168.10.200
EOF

echo "Configuration written to /etc/dnsmasq.d/playstation.conf"

# Test dnsmasq configuration
echo "Testing dnsmasq configuration..."
if dnsmasq --test; then
    echo "Configuration syntax OK"
else
    echo "Configuration error! Rolling back..."
    rm -f /etc/dnsmasq.d/playstation.conf
    exit 1
fi

# Restart dnsmasq
echo "Restarting dnsmasq..."
systemctl restart dnsmasq

# Verify it's running
if systemctl is-active --quiet dnsmasq; then
    echo "dnsmasq restarted successfully"
else
    echo "ERROR: dnsmasq failed to start!"
    systemctl status dnsmasq
    exit 1
fi

echo
echo "=== Setup Complete ==="
echo
echo "PlayStation domains will now resolve to 192.168.10.200"
echo
echo "Test with: dig @192.168.10.200 fus01.ps3.update.playstation.net"
echo
